asset_symbols = {
    "BTC": "bitcoin",
    "ETH": "ethereum",
    "USDT": "tether",
    "BNB": "binancecoin",
    "ADA": "cardano",
    "DOGE": "dogecoin",
    "XRP": "ripple",
    "SOL": "solana",
    "DOT": "polkadot",
    "MATIC": "matic-network",
    "LTC": "litecoin",
    "AVAX": "avalanche-2",
    "UNI": "uniswap",
    "LINK": "chainlink",
    "WBTC": "wrapped-bitcoin",
    "XLM": "stellar",
    "ALGO": "algorand",
    "BCH": "bitcoin-cash",
    "TRX": "tron",
    "SHIB": "shiba-inu",
}